#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#
#

# Get list of versions to be used by tests/check_for_new_version

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

get_versions(){
    curl -s http://archive.apache.org/dist/zookeeper/ |
    # no grep -P on Mac, requires GNU grep :-/
    egrep -i -o 'href="zookeeper-[[:digit:]]+(\.[[:digit:]]+)+(-[[:alpha:]]+)?' |
    grep -v -e alpha -e beta |
    sed 's/href="zookeeper-//'
}

get_versions
